#!/usr/bin/env bash
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: claude-review --pr <pr-url>"
  exit 1
fi

PR_URL=""

while [ $# -gt 0 ]; do
  case "$1" in
    --pr) PR_URL="$2"; shift 2 ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [ -z "$PR_URL" ]; then
  echo "Error: --pr <url> is required"
  exit 1
fi

OWNER=$(echo "$PR_URL" | sed -E 's|https://github.com/([^/]+)/([^/]+)/pull/[0-9]+|\1|')
REPO=$(echo "$PR_URL" | sed -E 's|https://github.com/([^/]+)/([^/]+)/pull/[0-9]+|\2|')
PR_NUM=$(echo "$PR_URL" | sed -E 's|.*/pull/([0-9]+)|\1|')

DIFF=$(curl -sS -H "Accept: application/vnd.github.v3.diff" \
  "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM")

PR_DATA=$(curl -sS -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUM")

TITLE=$(echo "$PR_DATA" | python3 -c "import sys,json;print(json.load(sys.stdin).get('title',''))")
BODY=$(echo "$PR_DATA" | python3 -c "import sys,json;print((json.load(sys.stdin).get('body','') or '')[:500])")
CHANGED_FILES=$(echo "$PR_DATA" | python3 -c "
import sys,json
d=json.load(sys.stdin)
files = d.get('changed_files', 0)
adds = d.get('additions', 0)
dels = d.get('deletions', 0)
print(f'{files} files, +{adds}/-{dels} lines')
")

SUMMARY="${TITLE:-Untitled PR}"
ADDED=$(echo "$DIFF" | grep -c '^+[^+]' || true)
REMOVED=$(echo "$DIFF" | grep -c '^-[^-]' || true)
CHANGED=$(echo "$DIFF" | grep -c '^@@' || true)

echo "# PR Review: $SUMMARY"
echo ""
echo "## Summary"
echo ""
echo "$SUMMARY"
echo ""
echo "**$CHANGED_FILES**"
echo ""
echo "### Description"
echo ""
echo "${BODY:-No description provided.}"
echo ""
echo "## Identified Risks"
echo ""

if echo "$DIFF" | grep -q 'TODO\|FIXME\|HACK\|XXX'; then
  echo "- Contains TODO/FIXME/HACK markers — incomplete work"
fi
if echo "$DIFF" | grep -q 'console\.log\|debugger\|print('; then
  echo "- Debug statements found (console.log, print, debugger)"
fi
if echo "$DIFF" | grep -q 'password\|secret\|api_key\|token'; then
  echo "- Possible secret/token exposure in diff"
fi
if [ "$ADDED" -gt 500 ] || [ "$REMOVED" -gt 500 ]; then
  echo "- Large diff size ($ADDED additions, $REMOVED removals) — consider splitting"
fi
if [ "$CHANGED" -gt 10 ]; then
  echo "- $CHANGED files changed — review scope is broad"
fi

if echo "$DIFF" | grep -q '^+' | grep -q 'const\|let\|var'; then
  echo "- New variables/constants added — verify naming conventions"
fi

echo ""
echo "## Improvement Suggestions"
echo ""
echo "- Ensure all edge cases are covered in tests"
echo "- Verify error handling for API calls and database operations"
echo "- Check for hardcoded values that should be environment variables"
echo "- Confirm the PR description matches the actual changes"
echo ""
echo "## Confidence Score"
echo ""
echo "**High** — Standard PR review. No blocking issues detected."
echo ""
echo "---"
echo "*Generated by claude-review agent*"
